### ISSUE TITLE
ERROR [karma]: [TypeError: undefined is not a function]

### ISSUE THREAD

**Issue by sashasochka** [usrz/javascript-karma-verbose-reporter#2]
Hi, sometimes I get this error.

```
ERROR [karma]: [TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /home/oleksandr/Projects/wdc/node_modules/karma-verbose-reporter/reporter.js:166:23
    at Array.forEach (native)
    at VerboseReporter.onSpecComplete (/home/oleksandr/Projects/wdc/node_modules/karma-verbose-reporter/reporter.js:165:11)
    at null.<anonymous> (/home/oleksandr/Projects/wdc/node_modules/karma/lib/events.js:15:22)
    at emitTwo (events.js:92:20)
    at emit (events.js:169:7)
    at onResult (/home/oleksandr/Projects/wdc/node_modules/karma/lib/browser.js:219:13)
    at Socket.<anonymous> (/home/oleksandr/Projects/wdc/node_modules/karma/lib/events.js:15:22)
    at emitOne (events.js:82:20)
    at Socket.emit [as $emit] (events.js:166:7)
[22:29:02] ~/Projects/wdc> vim /home/oleksandr/Projects/wdc/node_modules/karma-verbose-reporter/reporter.js
```

**Comment by sashasochka** [comment]
Just discovered, this happens if I use `dump` function. It actually _dumps_ value first, but then karma crashes completely.

**Comment by pfumagalli** [comment]
Which `dump` function? Do you have an example with which I can actually reproduce the issue?

**Comment by sashasochka** [comment]
`window.dump` function, here is the docs. https://developer.mozilla.org/en-US/docs/Web/API/Window/dump

Example: simple test case like this `it('test', () => { dump('hello'); })`

I used phantomjs.

**Comment by pfumagalli** [comment]
Hm, never heard of `window.dump(...)`, anyhow now HEAD should work (defaulting to `info` for any unrecognized level). Give it a shot!

**Comment by sashasochka** [comment]
Hm, this leads to a different error

```
PhantomJS 1.9.8 (Linux 0.0.0): Executed 0 of 11 SUCCESS (0 secs / 0 secs)
DUMP: 'polyfill DUMP'
PhantomJS 1.9.8 (Linux 0.0.0): Executed 1 of 11 SUCCESS (0 secs / 0.013 secs)
ERROR [karma]: [TypeError: Cannot read property 'isLevelEnabled' of undefined]
TypeError: Cannot read property 'isLevelEnabled' of undefined
    at Logger.(anonymous function) (/home/oleksandr/Projects/wdc/node_modules/karma/node_modules/log4js/lib/logger.js:74:35)
    at /home/oleksandr/Projects/wdc/node_modules/karma-verbose-reporter/reporter.js:165:37
    at Array.forEach (native)
    at VerboseReporter.onSpecComplete (/home/oleksandr/Projects/wdc/node_modules/karma-verbose-reporter/reporter.js:164:11)
    at null.<anonymous> (/home/oleksandr/Projects/wdc/node_modules/karma/lib/events.js:15:22)
    at emitTwo (events.js:92:20)
    at emit (events.js:169:7)
    at onResult (/home/oleksandr/Projects/wdc/node_modules/karma/lib/browser.js:219:13)
    at Socket.<anonymous> (/home/oleksandr/Projects/wdc/node_modules/karma/lib/events.js:15:22)
    at emitOne (events.js:82:20)
```

**Comment by pfumagalli** [comment]
Hmm... That's weird, I must have not understood the function call properly. Give it an update/shot now...

**Comment by sashasochka** [comment]
Thanks, now that works. Could you bump a version please?

**Comment by pfumagalli** [comment]
Fabulous! Thanks for checking :-) Just bumped to 0.0.3 and pushed to NPM.
