### ISSUE TITLE
Empty Test Suite results in error

### ISSUE THREAD

**Issue by rajsite** [usrz/javascript-karma-verbose-reporter#5]
I have a test suite that hangs the browser and times out without completing any tests (unrelated to the verbose reporter). It looks like this case might not be handled correctly by the verbose reporter:

verbose reporter v0.0.5

```
01 02 2017 12:18:04.546:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Starting tests 61443801
01 02 2017 12:19:04.550:WARN [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Disconnected (1 times), because no message i
n 60000 ms.
01 02 2017 12:19:04.550:ERROR [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Disconnected, because no message in 60000 m
s.
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  Disconnected, because no message in 60000 ms.
01 02 2017 12:19:04.553:WARN [karma]: Test suite was empty.
01 02 2017 12:19:04.554:ERROR [karma]: ReferenceError: call is not defined
    at E:\dev\github\VireoSDK\node_modules\karma-verbose-reporter\reporter.js:107:45
    at Array.forEach (native)
    at VerboseReporter.onRunComplete (E:\dev\github\VireoSDK\node_modules\karma-verbose-reporter\reporter.js:1
06:19)
    at Server.<anonymous> (E:\dev\github\VireoSDK\node_modules\karma\lib\events.js:13:22)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:191:7)
    at emitRunCompleteIfAllBrowsersDone (E:\dev\github\VireoSDK\node_modules\karma\lib\server.js:295:12)
    at Server.<anonymous> (E:\dev\github\VireoSDK\node_modules\karma\lib\server.js:326:7)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (E:\dev\github\VireoSDK\node_modules\karma\lib\server.js:309:12)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Timeout._onTimeout (E:\dev\github\VireoSDK\node_modules\karma\lib\browser.js:51:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
```

**Comment by pfumagalli** [comment]
Fixed by #6

**Comment by pfumagalli** [comment]
Pushed out on NPM in version 0.0.6

**Comment by rajsite** [comment]
Thanks!
